version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: my-app/Dockerfile
    ports:
      - "3004:3004"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=yoyo2015
      - DATABASE_NAME=myappdb
      - GOOGLE_APPLICATION_CREDENTIALS=/app/statisfy-backend/credentials.json
    volumes:
      - ../statisfy-backend:/app/statisfy-backend
    command: ["npm", "start"]
    networks:
      - my-network

  db:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yoyo2015
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Ensures data persists
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_data:   # This defines the persistent volume
